Заполняет попап
htmlacademy-javascript/1402843-keksobooking-21 pull request #3
Opened 2020-09-30 13:44 UTC by Bambukoz

2020-10-01 04:39 UTC, Shv-sergey70 requested changes

2020-10-01 04:39 UTC, Shv-sergey70 commented on js/main.js
> +const renderCard = (obj) => {
На вход хоть и приходит объект, но это объект какой-то сущности. Нужно дать именно ее название переменной

2020-10-01 04:39 UTC, Shv-sergey70 commented on js/main.js
> +const MIN_GUESTS = 1;
Две и более константы объединенные по смыслу стоит делать перечислением:
```
const Guests = {
  MIN: 1,
  MAX: 3
};
```
Пример оформления:
https://up.htmlacademy.ru/javascript/21/criteries#b8

2020-10-01 04:39 UTC, Shv-sergey70 commented on js/main.js
>  const PIN = {
Перечисление оформляется несколько иначе (см критерий Б8)

2020-10-01 04:39 UTC, Shv-sergey70 commented on js/main.js
> +const createAd = (arr) => {
Нужно дать более осмысленное название параметру

2020-10-01 04:39 UTC, Shv-sergey70 commented on js/main.js
> +  map.appendChild(fragment);
Тут незачем использовать фрагмент, учитывая что происходит только 1 вставка

2020-10-01 04:39 UTC, Shv-sergey70 commented on js/main.js
> +  const card = cardTemplate.cloneNode(true);
Тут можно сразу так:
```
const card = document.querySelector(`#card`).content.querySelector(`.popup`).cloneNode(true);
```
Незачем создавать переменную `cardTemplate`, так как она используется только в одном месте

2020-10-01 04:39 UTC, Shv-sergey70 commented on js/main.js
> +const declOfNum = (number, words) => words[(number % 100 > 4 && number % 100 < 20) ? 2 : [2, 0, 1, 1, 1, 2][(number % 10 < 5) ? number % 10 : 5]];
Судя по всему эта функция была взята откуда-то. Это ок, единственное - название нужно дать полноценное без сокращений (есть критерий)

2020-10-01 04:39 UTC, Shv-sergey70 commented on js/main.js
> +  }
Стоит придумать иное решение. Текущее не походит, так как ты жестко привязан к тем офферам, что есть в разметке и приходится создавать вложенный цикл.

Попробуй самостоятельно генерировать дом-элемент и вставлять его с нужным классом в контейнер. Тогда понадобится только один цикл.

2020-10-01 04:39 UTC, Shv-sergey70 commented on js/main.js
> +            type: getRandomIndex(Object.keys(TYPES)),
Касательно названия функции `getRandomIndex`  - она же не индекс возвращает, а элемент массива. Надо поправить название

2020-10-01 04:39 UTC, Shv-sergey70 commented on js/main.js
> +  const dataArr = arr;
А зачем это действие делать?

2020-10-01 07:43 UTC, Bambukoz commented on js/main.js
> +  const dataArr = arr;
Я иногда засиживаюсь и начинаю делать лишнее

2020-10-02 04:08 UTC, Shv-sergey70 requested changes

2020-10-02 04:08 UTC, Shv-sergey70 commented on js/main.js
> +      fragment.appendChild(photo.cloneNode(true)).src = dataObject.offer.photos[i];
Так как ты делаешь клонирование исходного фото, то будет более правильно его убрать из контейнера `popup__photos` и поместить в тег `template`, как это сделано для `card`, `pin`. Тогда также по аналогии можно будет копировать шаблон и использовать уже его при вставке

2020-10-02 04:08 UTC, Shv-sergey70 commented on js/main.js
> +      fragment.appendChild(photo.cloneNode(true)).src = dataObject.offer.photos[i];
Создавай отдельную переменную для этого действия `photo.cloneNode(true)).src = dataObject.offer.photos[i]`, так как передавать в `appendChild` значения из присваивания, это антипаттерн

2020-10-02 04:08 UTC, Shv-sergey70 commented on js/main.js
> +  photo.src = dataObject.offer.photos[0];
Если фото не будет, это действие бесполезно

2020-10-02 04:08 UTC, Shv-sergey70 commented on js/main.js
> +  map.appendChild(document.createDocumentFragment().appendChild(renderCard(card)));
Здесь зачем фрагмент создавать? Происходит единичная вставка, результат точно такой же по производительности, как если все было бы и без фрагмента

2020-10-02 04:08 UTC, Shv-sergey70 commented on js/main.js
> +const createBlocks = (arr) => {
Название `arr` - не подойдет, ты не знаешь что именно там лежит и не можешь сходу понять. Нужно дать такое название, которое будет отражать сущность того что там находится

2020-10-02 16:30 UTC, Shv-sergey70 commented on js/main.js
> +const Prices = {
Название перечисления должно быть в единственном числе

2020-10-02 16:30 UTC, Shv-sergey70 commented on js/main.js
> +            y: getRandomRange(Locations.Y_MIN, Locations.Y_MAX)
Данные значения в `x, y` должны совпадать с теми что в `address`

2020-10-02 16:30 UTC, merged